# golangci-lint configuration for copy-image project
# This configuration is optimized for cross-platform builds
# ================================================================
version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - misspell
  disable:
    - exhaustive
    - wrapcheck
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - fmt.Sscanf
        - fmt.Fprintf
        - fmt.Printf
    gocritic:
      disabled-checks:
        - ifElseChain
    gosec:
      excludes:
        - G104
        - G304
        - G107
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - frontend
      - build
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - copy-image
  exclusions:
    generated: lax
    paths:
      - frontend
      - build
      - third_party$
      - builtin$
      - examples$
