// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCopy() {
  return window['go']['main']['App']['CancelCopy']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function ScanFiles() {
  return window['go']['main']['App']['ScanFiles']();
}

export function SelectDestFolder() {
  return window['go']['main']['App']['SelectDestFolder']();
}

export function SelectSourceFolder() {
  return window['go']['main']['App']['SelectSourceFolder']();
}

export function StartCopy(arg1) {
  return window['go']['main']['App']['StartCopy'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
