// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CancelCopy():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentVersion():Promise<string>;

export function PerformUpdate(arg1:string):Promise<boolean>;

export function SaveConfig():Promise<void>;

export function ScanFiles():Promise<Array<string>>;

export function SelectDestFolder():Promise<string>;

export function SelectSourceFolder():Promise<string>;

export function StartCopy(arg1:boolean):Promise<main.CopyResult>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
